### ISSUE TITLE
Failure Installing QXmlEdit on Ubuntu 18.04 (QML Module Missing)

### ISSUE THREAD

**Issue by haleba-hotmail** [lbellonda/qxmledit#95]
Following the instructions in the source package's "INSTALL" file:

> _"Extract the source, go to top folder
>  qmake
>  make
>  sudo make install"_

I'm encountering an issue almost identical to the one in Issue #93   ["Installation fail on Ubuntu 23.10 #93"](https://github.com/lbellonda/qxmledit/issues/93)

In my case the error was

    Project ERROR: Unknown module(s) in QT: xmlpatterns svg qml
    Makefile:90: recipe for target 'sub-src-QXmlEditWidget-pro-make_first-ordered' failed
    make: *** [sub-src-QXmlEditWidget-pro-make_first-ordered] Error 3

Following the advice in Issue #93 I installed the development version libqt5xmlpatterns-dev and the xmlpatterns error disappeared. Installing the "-dev" version of libqt5svg solved the svg error, **_but there doesn't appear to be a development version libqt5qml,_** so it looks like I'm out of luck.

All  of the Qt5 libraries are Qt version 5.9.5

Any advice would be greatly appreciated.

**Comment by lbellonda** [comment]
Hello, I found this solution in a Ubuntu forum, but currently I am unable to test it myself:

install qtdeclarative5-dev  package.

Let me know if you have still problems.
Best regards.

**Comment by haleba-hotmail** [comment]
Thanks for following up. My post-mortem detective work also found qtdeclarative5-dev as the qml source.

Things were looking good the next try, it was taking forever and a day to compile so I thought I was home free until ...

    Project ERROR: Unknown module(s) in QT: scxml
    Makefile:176: recipe for target 'sub-src-QXmlEdit-pro-make_first-ordered' failed
    make: *** [sub-src-QXmlEdit-pro-make_first-ordered] Error 3

I was like "You've got to be f*g kidding ..".

A little more detective work turned up:

> _"The next new module is Qt SCXML. It’s a completely new module that makes it very easy to integrate SCXML based state machines into Qt. It builds directly on top of the Qt Statemachine framework and extends it with with both a SCXML to C++ compiler and a runtime that allows loading SCXML based state machines."_

[**"Qt 5.7 released" (6/16/2016) - Qt Group Blog**](https://www.qt.io/blog/2016/06/16/qt-5-7-released)

Debian and others have Qt5 SCXML packages, but Muon Package Manager came up blank for any SCXML packages of any kind, so it seems that maybe this was too new to have been done for Ubuntu 18.04.

No sign of the SCXML packages on pkgs.org until Ubuntu 20.04 (  [**"Search Results for qt5scxml"**](https://pkgs.org/search/?q=qt5scxml))

And then I found ..

> _"Neither Ubuntu 20.04 nor Ubuntu 20.10 ship Qt SCXML's private development files such as 'qscxmlstatemachine_p.h'. These files are present in 20.04's qtscxml-everywhere-src_5.12.8.orig.tar.xz and 20.10's qtscxml-everywhere-src_5.14.2.orig.tar.xz but are not being packaged._

> _"This problem is not present in the Ubuntu 21.XX series due to the inclusion of the libqt5scxml5-private-dev package._

> _"This problem is not present in CentOS 8 which also ships Qt 5.12 modules."_

[**"Missing Qt5 SCXML private dev files" (11/13/2021) - Launchpad Bugs: qtscxml-everywhere-src package**](https://bugs.launchpad.net/ubuntu/+source/qtscxml-everywhere-src/+bug/1950857)

So I tried qt4-default, but that gave a whole bunch of errors

    /usr/include/qt4/QtGui/qtransform.h:383:17: error: implicitly-declared ‘QTransform::QTransform(    const QTransform&)’ is deprecated [-Werror=deprecated-copy]
      383 | { QTransform t(a); t *= n; return t; }
          |                 ^
    /usr/include/qt4/QtGui/qtransform.h:136:17: note: because ‘QTransform’ has user-provided     ‘QTransform& QTransform::operator=(const QTransform&)’
      136 |     QTransform &operator=(const QTransform &);
          |                 ^~~~~~~~

The only other thing to try is resetting to Qt5 and seeing if the Ubuntu 20.04 SCXML package works in 18.04.

**Comment by lbellonda** [comment]
Hello, SCXML is an optional package and can be disabled via environment variable or via command line as described in the INSTALL file. Mi advice is to disable it, because it covers only a specific feature not very popular.
The main features of the editor will be available anyway.

**Comment by haleba-hotmail** [comment]
OK Mr. @lbellonda , I set `QXMLEDIT_DISABLE_SCXML="Y"` and _**finally**_ got a clean installation, but then I ran into the error in ("build fail - warnings treated as errors - variable defined and not used" Issue #48)

    /opt/qxmledit/qxmledit: error while loading shared libraries: libQXmlEditWidget-0.9.9.so.0: 
    cannot     open shared object file: No such file or directory

_"Nooooooo.."._

Took a deep breath and patient searching turned up Issue 48.

instead of writing a script when there was a desktop file ready to go I delved into setting all this permanently. I tried setting both `PATH` and  `LD_LIBRARY_PATH` in a profile.d script but only the path change took after rebooting.

After a crash refresher course in setting environment variables I added the library path in bash.bashrc

    #Custom commands
    shopt -s globstar
    alias cat-nocolor="sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g'"
    export TERM="xterm-mono"
    force_color_prompt=no
    export LD_LIBRARY_PATH="/opt/qxmledit"

and QXmlEdit is working (Yay!)

Will probably put the /opt path in together with the library path in bash.bashrc at some point, but just leaving well enough alone after all this.

Only outstanding issue is that it can only be run from the terminal. I tried putting the desktop file in /usr/share/applications and double-clicking in /opt/qxmledit but I only get a brief "spin-dry" entry in the taskbar and QXmlEdit fails to run. dex has no problems running the GUI with the desktop file

    dex -v /opt/qxmledit/QXmlEdit.desktop
    Autostart file: /opt/qxmledit/QXmlEdit.desktop
    Executing command: /opt/qxmledit/qxmledit


, so there must be some issue with KDE. Maybe I should use your solution and set up a KDE Application Launcher menu item that calls on the script instead of the application.

**Comment by lbellonda** [comment]
This kind of packaging is outside of the scope of this site. Some distributions integrate QXmlEdit (Suse, Fedora,...) maybe you might take a look to the configuration of their packages.
